"""Research Figures — gallery of analysis figures from the pipeline."""

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

import streamlit as st

from utils import APP_BG, FIGURES_DIR, MUTED_TEXT, TEXT_COLOR, apply_theme

st.set_page_config(page_title="Research Figures", layout="wide")
apply_theme()
st.title("📈 Research Figures")

st.markdown(
    f'<div style="color: {MUTED_TEXT}; margin-bottom: 24px;">'
    f"Gallery of all analysis figures generated by the capstone pipeline. "
    f"Click any image to expand.</div>",
    unsafe_allow_html=True,
)

if not FIGURES_DIR.exists():
    st.warning(f"Figures directory not found: `{FIGURES_DIR}`")
    st.stop()


# ---------------------------------------------------------------------------
# Organize figures by category
# ---------------------------------------------------------------------------

CATEGORIES = {
    "Shot Charts & Density": {
        "shot_chart_2025-26.png": "Full-court shot chart for the 2025-26 season with all attempted shots plotted by location.",
        "shot_density_hexbin_2025-26_dark.png": "Hexbin density heatmap (dark theme) showing where shots are most frequently taken.",
        "shot_density_hexbin_2025-26_light.png": "Hexbin density heatmap (light theme) — same data, lighter styling.",
        "shot_distance_analysis_2025-26.png": "Shot distance distribution and FG% by distance band.",
    },
    "GAM Analysis (Shot Probability Model)": {
        "gam_effect_distance.png": "GAM partial dependence: how shot distance affects make probability (log-odds).",
        "gam_effect_angle.png": "GAM partial dependence: effect of shot angle on make probability.",
        "gam_effect_clock.png": "GAM partial dependence: game clock's effect on shot probability.",
        "gam_effect_period.png": "GAM partial dependence: how period/quarter affects shot probability.",
        "gam_effect_shot_types.png": "Bar chart of shot-type effects from a shot-type-only GAM.",
        "gam_spatial_probability.png": "Spatial probability heatmap — predicted FG% across the court surface.",
        "gam_spatial_tensor.png": "Tensor product smooth visualizing the spatial surface of the GAM.",
    },
    "SDI & Player Clustering": {
        "sdi_vs_xfg_scatter.png": "Shot Difficulty Index vs Actual FG% scatter plot. Color = FG% residual, size = volume.",
        "player_archetypes_scatter.png": "PCA scatter of player archetypes from GMM clustering.",
        "gmm_bic_by_role.png": "BIC vs k for each role group — used for optimal cluster selection.",
        "player_metric_correlations.png": "Correlation heatmap across player-level shooting metrics.",
    },
    "Model Calibration": {
        "calibration_reliability_2025-26.png": "Overall xFG model reliability diagram — predicted vs observed FG%.",
        "calibration_by_distance_2025-26.png": "Calibration curves split by distance band.",
    },
    "Value Analysis (POE vs Salary)": {
        "poe_vs_salary_scatter.png": "Points Over Expected vs Salary scatter — highlights best-value and overpaid players.",
        "fg_residual_vs_salary_scatter.png": "FG% Residual vs Salary scatter — alternative value perspective.",
    },
    "Player Spotlights": {
        "Stephen_Curry_poe_shotchart.png": "Stephen Curry POE-colored shot chart — green = overperform, red = underperform.",
        "Shai_Gilgeous-Alexander_poe_shotchart.png": "Shai Gilgeous-Alexander POE-colored shot chart.",
        "Nikola_Jokić_residual_heatmap.png": "Nikola Jokić residual heatmap — spatial over/under performance.",
        "Luke_Kennard_residual_heatmap.png": "Luke Kennard residual heatmap.",
    },
}


for category, figures in CATEGORIES.items():
    with st.expander(f"**{category}**", expanded=True):
        # Determine columns per row (max 3)
        items = [(name, desc) for name, desc in figures.items() if (FIGURES_DIR / name).exists()]
        if not items:
            st.caption("No figures found for this category.")
            continue

        cols_per_row = min(len(items), 3)
        for i in range(0, len(items), cols_per_row):
            batch = items[i : i + cols_per_row]
            cols = st.columns(len(batch))
            for col, (fname, desc) in zip(cols, batch):
                with col:
                    st.image(str(FIGURES_DIR / fname), use_container_width=True)
                    st.caption(desc)
